### ISSUE TITLE
Eating too much host memory

### ISSUE THREAD

**Issue by yueyang130** [deepmind/dqn_zoo#15] opened 2022-01-30 12:45 UTC
When I run the your code, specifically Rainbow Agent on Atari 100k, it consumes too much memory. One running need about 50GB memory per hour running. The below picture shows the memory overview when running two scripts.

Do you have any idea why it need such a big memory? Thanks for any advice.

![image](https://user-images.githubusercontent.com/55612720/151700154-1edae14f-0fd2-42e4-9268-a116f2959493.png)

**Comment by GeorgOstrovski** [comment] 2022-02-07 18:41
Thank you for reporting this. We have not observed such excessive memory usage with this code in our setup and default configuration - usually memory consumption lies well below 20GiB. 

Can I check what modifications you have applied to the code that you run? In particular, increasing the replay buffer size, or disabling image-downscaling/greyscaling in the preprocessing pipeline could easily lead to an increase in memory requirements.

**Comment by qsh-zh** [comment] 2022-02-14 16:50
encountered the same issue. Without any code modification, 
```shell
python3 -m dqn_zoo.dqn.run_atari
```
memory usage goes high to 100GB.

**Comment by GeorgOstrovski** [comment] 2022-07-08 10:45
Closing this for now - we could not reproduce the problem. If you are still experiencing the issue, please provide us with some more context when re-opening it, in particular let us know which local modifications were applied to the code.

**Closed by GeorgOstrovski** 2022-07-08 10:45 UTC
