### ISSUE TITLE
Memory issues when running with Docker

### ISSUE THREAD

**Issue by YasserdahouML** [deepmind/dqn_zoo#17] opened 2022-09-07 13:02 UTC
Hello,

I tried to run QR QDN on Atari keeping your initial setup (1 million frame per iteration and 200 iterations). The memory usage increases linearly until the system kills the process.

I used the run.sh that launches a docker image.

Would you please help with that?

Thanks

**Comment by jqdm** [comment] 2022-09-09 10:17
Could you confirm the latest version of the code is being used, with all recent commits? Have you made any local modifications? Also just to check, how much memory is being used?

We've not observed memory issues when running internally, though this is without Docker. Memory usage should plateau once the replay is full. Could be worth trying to run the agent without Docker to see if that still has memory issues. Dependencies are listed [here](https://github.com/deepmind/dqn_zoo/blob/master/docker_requirements.txt).

**Comment by YasserdahouML** [comment] 2022-09-09 10:29
Hi, I actually tried without docker cpu and it runs smoothly, the memory usage is when I run through docker.

I did not change anything, the repo code as it is.

**Comment by YasserdahouML** [comment] 2022-09-11 18:37
sure, what's the env required to run on GPU? should it be cuda 11.1.1 and nvidia driver 455?

**Comment by jqdm** [comment] 2022-09-20 11:06
Instructions for GPU support can be found on the JAX installation docs [here](https://github.com/google/jax#pip-installation-gpu-cuda), but CUDA 11.1 should work.

**Comment by jqdm** [comment] 2022-09-20 11:13
I've not been able to reproduce the memory issue with Docker on my desktop, the memory usage plateaus as expected when I try. Was there anything special about your Docker setup, e.g. which version of Docker are you using? I assume you set `--jax_platform_name=cpu`.

**Comment by jqdm** [comment] 2023-01-03 12:35
Closing as unable to reproduce and this issue seems specific to when running with Docker in a certain way rather than anything in the agent code itself. Feel free to reopen if you have any more information that would help with reproducing.

**Closed by jqdm** 2023-01-03 12:35 UTC
